# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function returns sum of minimum peptide/spectra count across AP-MS
#' runs.
#' @title GetPPN
#' 
#' @param mat A matrix of peptide/spectra count in the format of 
#' proteins (column) by AP-MS runs (row)
#' @return A matrix of proteins by proteins indicating sum of minimum 
#' peptide/spectra count across all AP-MS runs.
#' @author Qingzhou Zhang, \email{zqzneptune@hotmail.com}
#' @references Guruharsha, K. G., et al. "A protein complex network of 
#' Drosophila melanogaster." Cell 147.3 (2011): 690-703.
#' \url{https://doi.org/10.1016/j.cell.2011.08.047}
#' @examples
#' GetPPN(mat)
#' 
GetPPN <- function(mat) {
    .Call('_SMAD_GetPPN', PACKAGE = 'SMAD', mat)
}

